export interface FeedItem {
    "url": string;
    "source": number;
    "created": number;
    "user_id": number;
    "visible": number;
    "comments": string;
    "social_feed_id": number;
    "social_post_id": string;
    "social_id": string;
    "phash": any;
    "height": number;
    "width": number;
    "original_image": string;
    "author": string;
    "embed": string;
    "image": string;
    "title": string;
    "timestamp": number;
    "original_timestamp": number;
    "tweet_post_id": string;
    "post_id": string;
    "user_rights": {},
    "nsfw_score": any;
    "language": "en",
    "likes_count": any;
    "shares_count": any;
    "replies_count": any;
    "description": any;
    "cta": string;
    "highlight": boolean
    "pinned": boolean
    "recur_frequency": string;
    "recur_offset": string;
    "geo": {
        "city": string;
        "region": string;
        "country": string;
        "country_code": string;
        "latitude": string;
        "longitude": string;
        "lat": string;
        "lng": string;
        "geo_enabled": false
    },
    "tags": string[],
    "popup_function": string;
    "tweet_urls": string[],
    "retweeted_by": string;
    "custom_field": any,
    "offset": number;
    "ref_timestamp": number;
    "unique_offset": number;
    "relative_offset": number;
}